echo "GINGKO\n\n"
configs="CONFIG_MACH_XIAOMI_C3J  CONFIG_BACKLIGHT_KTD3136  CONFIG_INPUT_FINGERPRINT CONFIG_FINGERPRINT_FPC1020 CONFIG_FINGERPRINT_GF3208  CONFIG_NFC_NQ  CONFIG_TOUCHSCREEN_FTS_C3J CONFIG_TOUCHSCREEN_XIAOMI_C3J"
for c in $configs; do 
	grep $c .config
done

echo "\nLAUREL\n\n"

laurel="CONFIG_MACH_XIAOMI_F9S  CONFIG_INPUT_FINGERPRINT CONFIG_FINGERPRINT_GOODIX_FOD CONFIG_TOUCHSCREEN_TID_SUPPORT CONFIG_TOUCHSCREEN_TID_OPENSHORT_TEST CONFIG_TOUCHSCREEN_TID_OPENSHORT_TEST_STORE_RESULT  CONFIG_REGULATOR_GPIO   CONFIG_TOUCHSCREEN_GOODIX_F9S CONFIG_TOUCHSCREEN_FTS_F9S"
for l in $laurel; do
	grep $l .config
done
